### ISSUE TITLE
Error: Cannot find module 'vueify'

### ISSUE THREAD

**Issue by lucasmichot** [laracasts/Laravel-Elixir-Vueify-Setup#1]
Hello @JeffreyWay , I am facing issue while upgrading `larave-elixir`. So I've tried to build this test repo with different versions of node using NVM, all builds are failing for various versions:

``` sh
lucas@air:~/Gits/laracasts/Laravel-Elixir-Vueify-Setup [master] $ nvm ls
->      v0.12.7
         v4.1.0
```

Here is my build script:

``` sh
nvm use 0.12.7 # use Node 0.12.7
rm -rf node_modules # ensure we start from scratch between each build tests
npm install -g gulp # ensure gulp is installed globally for each Node versions
npm install
gulp
```

Only some basic warnings for `npm install`:

```
npm WARN peerDependencies The peer dependency babel-preset-es2015@^6.1.2 included from vueify will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
```

Here is the output:

```
[12:51:14] Using gulpfile ~/Gits/laracasts/Laravel-Elixir-Vueify-Setup/gulpfile.js
[12:51:14] Starting 'default'...
[12:51:14] Starting 'browserify'...
[12:51:15] 'browserify' errored after 945 ms
[12:51:15] Error: Cannot find module 'vueify'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/lucas/Gits/laracasts/Laravel-Elixir-Vueify-Setup/node_modules/laravel-elixir/tasks/browserify.js:95:13
    at Array.forEach (native)
    at browserifyStream (/Users/lucas/Gits/laracasts/Laravel-Elixir-Vueify-Setup/node_modules/laravel-elixir/tasks/browserify.js:93:39)
    at null.definition (/Users/lucas/Gits/laracasts/Laravel-Elixir-Vueify-Setup/node_modules/laravel-elixir/tasks/browserify.js:55:13)
    at Task.run (/Users/lucas/Gits/laracasts/Laravel-Elixir-Vueify-Setup/node_modules/laravel-elixir/Task.js:96:17)
    at Gulp.<anonymous> (/Users/lucas/Gits/laracasts/Laravel-Elixir-Vueify-Setup/node_modules/laravel-elixir/index.js:94:52)
[12:51:15] Error in plugin 'run-sequence'
Message:
    An error occured in task 'browserify'.
```

Tried to manuall add `vueify`, but another error occurs:

``` sh
lucas@air:~/Gits/laracasts/Laravel-Elixir-Vueify-Setup [master*] $ npm install vueify --save
npm WARN peerDependencies The peer dependency vueify-insert-css@^1.0.0 included from vueify will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency babel-runtime@^6.0.14 included from vueify will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency babel-preset-es2015@^6.1.2 included from vueify will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency babel-plugin-transform-runtime@^6.1.2 included from vueify will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency vue-hot-reload-api@^1.2.0 included from vueify will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

```
lucas@air:~/Gits/laracasts/Laravel-Elixir-Vueify-Setup [master*] $ gulp
[13:05:17] Using gulpfile ~/Gits/laracasts/Laravel-Elixir-Vueify-Setup/gulpfile.js
[13:05:17] Starting 'default'...
[13:05:17] Starting 'browserify'...

Fetching Browserify Source Files...
   - resources/assets/js/main.js


Saving To...
   - public/js/main.js

[13:05:19] Finished 'default' after 2.38 s
[13:05:27] gulp-notify: [Laravel Elixir] Browserify Failed!: Couldn't find preset "react" relative to directory "/Users/lucas/Gits/laracasts/Laravel-Elixir-Vueify-Setup/resources/assets/js" while parsing file: /Users/lucas/Gits/laracasts/Laravel-Elixir-Vueify-Setup/resources/assets/js/main.js
{ [Error: Couldn't find preset "react" relative to directory "/Users/lucas/Gits/laracasts/Laravel-Elixir-Vueify-Setup/resources/assets/js" while parsing file: /Users/lucas/Gits/laracasts/Laravel-Elixir-Vueify-Setup/resources/assets/js/main.js]
  filename: '/Users/lucas/Gits/laracasts/Laravel-Elixir-Vueify-Setup/resources/assets/js/main.js',
  stream:
   { _readableState:
      { highWaterMark: 16,
        buffer: [],
        length: 0,
        pipes: [Object],
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        objectMode: true,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null,
        resumeScheduled: false },
     readable: true,
     domain: null,
     _events:
      { end: [Object],
        error: [Object],
        data: [Function: ondata],
        _mutate: [Object] },
     _maxListeners: undefined,
     _writableState:
      { highWaterMark: 16,
        objectMode: true,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        buffer: [],
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false },
     writable: true,
     allowHalfOpen: true,
     _options: { objectMode: true },
     _wrapOptions: { objectMode: true },
     _streams: [ [Object] ],
     length: 1,
     label: 'deps' } }
[13:05:27] Finished 'browserify' after 9.94 s
```

Am I missing something ?

**Comment by vinkla** [comment]
What if you add the babel preset to your package.json?

``` json
"babel": {
  "presets": [
    "es2015",
    "react"
  ]
},
```

This is the same as adding a `.babelrc` file in the root of your project.

**Comment by lucasmichot** [comment]
> What is you add the babel preset to your package.json?

@vinkla, I've just tried but it does not help.
BTW, It seems to be already defined at https://github.com/laravel/elixir/blob/master/Config.js#L268 and https://github.com/laravel/elixir/blob/master/Config.js#L297

**Comment by vinkla** [comment]
Yeah, it was just a thought. I had similar error message and fixed it by adding the preset.

**Comment by JeffreyWay** [comment]
Can you upgrade to npm 3 and try again?

**Comment by lucasmichot** [comment]
Indeed @JeffreyWay, this is only working with versions (out of the box):
- `v5.0.0 (npm v3.3.6)`
- `v5.1.0 (npm v3.3.12)`

https://nodejs.org/en/download/releases/

It is also possible to make it work with a previous version, but `npm update -g npm` is required.

I think it is worth writing in the readme file (or saying it the related larcast video).

**Comment by lucasmichot** [comment]
Also worth mentioning it: as we need to build the assets to launch specific tests on Laravel, Travis-CI and CircleCI (not to mention others CI) don't support `5.x.x` versions.
- https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Provided-Node.js-Versions
- https://circleci.com/docs/environment#node-js

`npm update -g npm` will thus have to be also done in these situations.
